### ISSUE TITLE
post requests

### ISSUE THREAD

**Issue by sger** [romaonthego/AFXAuthClient#3]
retrieve post requests without authorization if token is saved to NSUserDefaults?

**Comment by romaonthego** [comment]
I'm not sure what you mean.

**Comment by sger** [comment]
if you call 

NSMutableURLRequest *request = [client requestWithMethod:@"POST" path:@"/v2/user/info" parameters:nil];

without authentication doesnt work.

**Comment by sger** [comment]
my solution is to save token credentials

**Comment by romaonthego** [comment]
You need to store AFXAuthToken information and retrieve it when you perform requests.
